# Generated by Django 2.2.6 on 2019-10-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('nutrition', models.CharField(max_length=30)),
                ('origin', models.CharField(max_length=30)),
                ('product_image', models.CharField(max_length=1000)),
            ],
            options={
                'unique_together': {('name', 'origin')},
            },
        ),
    ]
